Repository three-ping/SyncDay_Front, pull requests merged in 2024-12, with the labels that each got.

#45 refactor: 카드보드 레이아웃 수정
  src/assets/styles/syncday/components.css
  src/assets/styles/syncday/container.css
  src/assets/styles/syncday/layout.css
  src/components/SideBar.vue
  src/main.js
  src/views/proj/GithubCallback.vue
  src/views/proj/ProjMainPage.vue
  src/views/proj/ProjectView.vue
  src/views/proj/SideBar/ProjItem.vue
  src/views/proj/SideBar/WorkspaceItem.vue
  src/views/proj/components/NewProjModal.vue
  src/views/proj/components/ProjectSettingsModal.vue
  src/views/proj/components/ProjectView.vue
  src/views/proj/components/VCSOrgModal.vue
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/components/Card.vue
  src/views/workspace/components/CardItem.vue
  src/views/workspace/views/CardBoardView.vue
  src/views/workspace/views/KanbanBoardView.vue
Labels: fix🛠️, FrontEnd🖌️

#47 feat: 회의실 예약정보 확인 및 회의실 예약 삭제
  src/components/Navigation.vue
  src/router/meetingroom.js
  src/views/meetingroom/.txt
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
  vite.config.js
Labels: feat✨, FrontEnd🖌️

#48 chore: 임시 커밋
  SyncDay_Front.iml
  package-lock.json
  src/assets/icons/Gitlab.svg
  src/components/Navigation.vue
  src/views/search/SearchResult.vue
  src/views/search/components/CardboardSearch.vue
  src/views/search/components/ProjectSearch.vue
  src/views/search/components/WorkspaceSearch.vue
Labels: feat✨, FrontEnd🖌️

#49 [회의실] 회의실 예약 삭제
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
Labels: feat✨, FrontEnd🖌️

#50 [일정초대] 초대된 일정 확인 페이지 추가
  src/App.vue
  src/components/Assistant.vue
  src/components/Navigation.vue
  src/router/index.js
  src/router/inviation.js
  src/views/invitation/InvitationRoot.vue
  src/views/invitation/InvitationView.vue
Labels: feat✨, FrontEnd🖌️

#52 [회의실] 회의실 예약 코드 수정
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
Labels: FrontEnd🖌️, refactor✂️

#53 [팀] 팀 게시판 기능 추가
  src/router/index.js
  src/router/team.js
  src/stores/team.js
  src/views/team/TeamBoardEdit.vue
  src/views/team/TeamBoardView.vue
  src/views/team/TeamPostCreate.vue
  src/views/team/TeamPostDetailView.vue
  src/views/team/TeamPostView.vue
  src/views/team/TeamRoot.vue
  src/views/team/components/BoardPost.vue
  src/views/team/components/PostComment.vue
Labels: feat✨, FrontEnd🖌️

#54 feat(schedule) : 일정 등록, 조회, 수정, 삭제 기능
  package-lock.json
  package.json
  src/assets/images/alarm-clock.svg
  src/assets/images/alert.svg
  src/assets/images/attendee.svg
  src/assets/images/clock.svg
  src/assets/images/delete.svg
  src/assets/images/meeting.svg
  src/assets/images/update.svg
  src/components/Assistant.vue
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
  src/views/calendar/component/CalendarViewModal.vue
  src/views/proj/ProjMainPage.vue
  vite.config.js
Labels: feat✨, FrontEnd🖌️

#55 카드 검색 기능 추가
  src/components/Navigation.vue
  src/router/project.js
  src/views/search/SearchResult.vue
  src/views/search/components/CardSearch.vue
  src/views/search/components/CardboardSearch.vue
  src/views/search/components/ProjectSearch.vue
  src/views/search/components/WorkspaceSearch.vue
  src/views/search/useSearch.js
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/views/CardBoardView.vue
Labels: feat✨, FrontEnd🖌️

#57 [워크스페이스] 워크스페이스 추가(생성)
  package-lock.json
  package.json
  src/views/proj/ProjectView.vue
  src/views/proj/components/ProjectSettingsModal.vue
Labels: feat✨, FrontEnd🖌️

#60 [카드보드] 카드보드 생성
  src/views/proj/ProjectView.vue
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/views/CardBoardView.vue
  src/views/workspace/views/KanbanBoardView.vue
Labels: feat✨, FrontEnd🖌️

#61 [메인페이지] 위젯 / 비서 기능 수정
  src/App.vue
  src/components/Assistant.vue
  src/views/invitation/InvitationAccept.vue
  src/views/user/.txt
  src/views/user/Main.vue
  src/views/user/components/MainCalendar.vue
  src/views/user/components/ScheduleInvitaion.vue
  src/views/user/components/TeamBoardList.vue
Labels: FrontEnd🖌️, refactor✂️

#62 [채팅] 채팅 메세지 전송
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: feat✨, FrontEnd🖌️

#63 [채팅] 채팅창 아이콘 팝업 수정
  src/components/Navigation.vue
  src/views/chat/ChatRoomList.vue
Labels: fix🛠️, FrontEnd🖌️

#64 refactor(schedule) : 일정 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
  src/views/calendar/component/CalendarViewModal.vue
Labels: FrontEnd🖌️, refactor✂️

#66 [채팅] 디자인 수정
  src/router/index.js
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: fix🛠️, FrontEnd🖌️

#69 회의실 예약 디자인 수정
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
  src/views/workspace/WorkspaceView.vue
Labels: FrontEnd🖌️, refactor✂️

#70 회의실 css수정
  src/views/meetingroom/Meetingroom.vue
Labels: FrontEnd🖌️, refactor✂️

#71 [채팅] 채팅방 데이터 불러오기
  package-lock.json
  package.json
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
Labels: fix🛠️, FrontEnd🖌️

#72 refactor(schedule) : 일정 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
  src/views/calendar/component/CalendarViewModal.vue
  vite.config.js
Labels: FrontEnd🖌️, refactor✂️

#76 [카드태그] 카드 태그 생성 삭제
  src/components/Assistant.vue
  src/main.js
  src/views/chat/ChatRoom.vue
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
  src/views/proj/ProjectView.vue
  src/views/proj/components/ProjectSettingsModal.vue
  src/views/workspace/WorkspaceView.vue
Labels: feat✨, FrontEnd🖌️

#79 [채팅] 새 채팅 생성
  src/components/Navigation.vue
  src/router/index.js
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: feat✨, fix🛠️, FrontEnd🖌️

#80 [회의실 예약] 회의실 예약시 내용 저장 안되는 오류 수정
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomReservation.vue
  vite.config.js
Labels: FrontEnd🖌️, refactor✂️

#81 [채팅] 채팅방 나가기 후 삭제
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: feat✨, fix🛠️, FrontEnd🖌️

#83 [채팅] 채팅방 나가기 수정
  src/views/chat/ChatRoom.vue
Labels: fix🛠️, FrontEnd🖌️

#85 [프로젝트] 프로젝트 멤버 추가 삭제 기능
  src/views/proj/ProjMainPage.vue
  src/views/proj/components/ProjectSettingsModal.vue
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/views/KanbanBoardView.vue
Labels: feat✨, FrontEnd🖌️

#86 [채팅] 채팅방 입장 시 최신순으로 조회
  src/views/chat/ChatRoom.vue
  vite.config.js
Labels: fix🛠️, FrontEnd🖌️

#87 [채팅] 색상 수정
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: fix🛠️, FrontEnd🖌️

#90 refactor(schedule) : 일정 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
  vite.config.js.timestamp-1733542714714-c22633a55ea95.mjs
Labels: FrontEnd🖌️, refactor✂️

#92 feature: 카드 생성
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomReservation.vue
  src/views/proj/ProjMainPage.vue
  src/views/proj/SideBar/WorkspaceItem.vue
  src/views/proj/components/ProjectSettingsModal.vue
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/components/RepoSettingModal.vue
  src/views/workspace/components/layout/CardModal.vue
  src/views/workspace/views/CardBoardView.vue
  src/views/workspace/views/KanbanBoardView.vue
Labels: feat✨, FrontEnd🖌️

#94 [채팅] 디자인 및 날짜 수정
  package.json
  src/views/chat/ChatRoom.vue
  src/views/chat/chat_components/NewChatRoom.vue
Labels: fix🛠️, FrontEnd🖌️

#93 [비서] 재연결 대기시간 및 알림 디자인 수정
  src/components/Assistant.vue
Labels: FrontEnd🖌️, refactor✂️

#95 [채팅] 마지막 메세지 가져오기 및 채팅방 디자인 수정
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
Labels: fix🛠️, FrontEnd🖌️

#96 feat(schedule) : 타인 일정 조회 기능
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
Labels: feat✨, FrontEnd🖌️

#100 [전체] css 수정
  src/App.vue
  src/assets/styles/syncday/colors.css
  src/assets/styles/syncday/components.css
  src/components/Assistant.vue
  src/components/Navigation.vue
  src/views/chat/chat_components/NewChatRoom.vue
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
  src/views/search/SearchResult.vue
  src/views/search/components/CardSearch.vue
  src/views/search/components/CardboardSearch.vue
  src/views/search/components/ProjectSearch.vue
  src/views/search/components/WorkspaceSearch.vue
  src/views/team/TeamBoardEdit.vue
  src/views/team/TeamBoardView.vue
  src/views/team/TeamPostCreate.vue
  src/views/team/TeamPostDetailView.vue
  src/views/team/TeamPostView.vue
  src/views/team/components/PostComment.vue
  src/views/user/LoginPage.vue
  src/views/user/Main.vue
Labels: FrontEnd🖌️, refactor✂️

#103 [채팅] '나가시겠습니까' 문구 수정
  src/views/chat/ChatRoom.vue
Labels: fix🛠️, FrontEnd🖌️

#105 refactor(schedule) : 일정 기능 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
  src/views/calendar/component/CalendarViewModal.vue
Labels: FrontEnd🖌️, refactor✂️

#104 refactor: 회의실 css수정
  src/main.js
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomDetails.vue
  src/views/meetingroom/MeetingroomReservation.vue
  src/views/team/TeamBoardEdit.vue
  src/views/user/components/ScheduleInvitaion.vue
Labels: FrontEnd🖌️, refactor✂️

#108 refactor(schedule) : 일정 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
Labels: FrontEnd🖌️, refactor✂️

#109 refactor: 코드 수정
  src/views/team/TeamBoardEdit.vue
Labels: FrontEnd🖌️, refactor✂️

#111 refactor: 로그인 페이지 수정
  src/views/user/LoginPage.vue
Labels: FrontEnd🖌️, refactor✂️

#114 [채팅] 채팅방 이름 불러오기 수정
  src/views/chat/ChatRoomList.vue
Labels: fix🛠️, FrontEnd🖌️

#115 refactor: 회의실 css 수정
  src/views/meetingroom/Meetingroom.vue
Labels: FrontEnd🖌️, refactor✂️

#116 refactor: 회의실 css 수정
  src/views/meetingroom/Meetingroom.vue
  src/views/meetingroom/MeetingroomReservation.vue
Labels: FrontEnd🖌️, refactor✂️

#119 refactor: 비밀번호 변경 화면 디자인 수정
  src/views/user/PassWordChange.vue
Labels: FrontEnd🖌️, refactor✂️

#118 refactor(schedule) : 일정 알람 수정
  src/views/calendar/component/CalendarModal.vue
  src/views/calendar/component/CalendarViewModal.vue
Labels: FrontEnd🖌️, refactor✂️

#120 refactor(schedule): 일정 직원 검색 및 참석자 검색 수정
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarModal.vue
Labels: FrontEnd🖌️, refactor✂️

#121 refactor(schedule) : 일정 참석자 목록 스크롤 수정
  src/views/calendar/component/CalendarViewModal.vue
Labels: FrontEnd🖌️, refactor✂️
