Repository three-ping/SyncDay_Front, pull requests merged in 2024-11, with the labels that each got.

#6 ADD: 비밀번호 변경 화면 구현
  package-lock.json
  package.json
  src/App.vue
  src/assets/images/lock.svg
  src/components/layout/Navigation.vue
  src/main.js
  src/plugins/axios.js
  src/router/index.js
  src/stores/auth.js
  src/views/main.vue
  src/views/user/LoginPage.vue
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
  vite.config.js
Labels: feat✨, FrontEnd🖌️

#7 ADD: 로그인 페이지 생성 및 rt 쿠키로부터 받아오도록 수정
  src/App.vue
  src/assets/images/syncdaylogo.svg
  src/components/layout/Navigation.vue
  src/plugins/axios.js
  src/router/index.js
  src/router/main.js
  src/router/user.js
  src/stores/auth.js
  src/views/user/LoginPage.vue
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
Labels: feat✨, fix🛠️, FrontEnd🖌️

#8 FIX: 유저 정보를 항상 들고 다니도록 수정.
  package-lock.json
  package.json
  src/assets/images/github-icon.svg
  src/assets/images/job.svg
  src/components/layout/Navigation.vue
  src/main.js
  src/plugins/axios.js
  src/stores/auth.js
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
Labels: fix🛠️, FrontEnd🖌️

#11 [회원] 프론트화면 rem으로 비율 수정
  src/App.vue
  src/components/layout/Navigation.vue
  src/components/layout/SideBar.vue
  src/plugins/axios.js
  src/router/index.js
  src/router/project.js
  src/stores/auth.js
  src/views/.txt
  src/views/Project/ProjectPage.vue
  src/views/user/LoginPage.vue
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
Labels: fix🛠️, FrontEnd🖌️

#12 FIX: nav바 수정 중
  src/App.vue
  src/components/layout/AppHeader.vue
  src/components/layout/Navigation.vue
  src/plugins/axios.js
  src/router/index.js
  src/stores/auth.js
  src/views/user/Mypage.vue
Labels: fix🛠️, FrontEnd🖌️

#13 로그인 페이지 수정 및 네브바 수정
  src/App.vue
  src/components/layout/Navigation.vue
  src/main.js
  src/plugins/axios.js
  src/router/index.js
  src/router/main.js
  src/stores/auth.js
  src/views/user/LoginPage.vue
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
Labels: fix🛠️, FrontEnd🖌️

#14 [Proj] ProjSideBarItem 초안 작성
  src/App.vue
  src/assets/styles/layout.css
  src/assets/styles/main.css
  src/assets/styles/variable.css
  src/components/layout/Navigation.vue
  src/components/layout/SideBar.vue
  src/router/project.js
  src/views/Proj/ProjMainPage.vue
  src/views/Proj/components/ProjItem.vue
  src/views/Proj/components/WorkSpaceItem.vue
  src/views/Project/ProjectPage.vue
  src/views/user/LoginPage.vue
Labels: FrontEnd🖌️

#17 feat: 사이드바 수정하고 프로젝트 정보 표시
  src/App.vue
  src/assets/styles/layout.css
  src/components/layout/SideBar.vue
  src/router/project.js
  src/views/Proj/ProjMainPage.vue
  src/views/Proj/components/ProjectView.vue
  src/views/Proj/components/SideBar/ProjItem.vue
  src/views/Proj/components/SideBar/WorkspaceItem.vue
  src/views/Proj/components/WorkSpaceItem.vue
  src/views/Proj/components/WorkspaceView.vue
Labels: FrontEnd🖌️

#20 feat: 프로젝트 페이지에서 워크스페이스 리스트 조회 화면 구현
  index.html
  src/App.vue
  src/assets/styles/layout.css
  src/components/layout/Navigation.vue
  src/components/layout/SideBar.vue
  src/router/project.js
  src/views/Proj/ProjMainPage.vue
  src/views/Proj/components/ProjectView.vue
  src/views/Proj/components/SideBar/ProjItem.vue
  src/views/Proj/components/SideBar/WorkspaceItem.vue
  src/views/Proj/components/WorkspaceView.vue
  src/views/Workspace/WorkspaceView.vue
  src/views/Workspace/components/Card.vue
  src/views/Workspace/components/layout/Board.vue
  src/views/Workspace/components/layout/CardModal.vue
  src/views/Workspace/views/CardBoardView.vue
  src/views/Workspace/views/KanbanBoardView.vue
Labels: feat✨, FrontEnd🖌️

#22 프로젝트 추가 로직 구현
  src/views/Proj/ProjMainPage.vue
Labels: feat✨, FrontEnd🖌️

#23 [Workspace] 프로젝트 화면에서 워크스페이스 추가 로직 생성
  src/views/Proj/ProjMainPage.vue
  src/views/Proj/components/ProjectView.vue
  src/views/Proj/components/SideBar/WorkspaceItem.vue
Labels: feat✨, FrontEnd🖌️

#27 feat(schedule) : 일정 조회 기능
  package-lock.json
  package.json
  src/router/calendar.js
  src/router/index.js
  src/views/calendar/CalendarRoot.vue
  src/views/calendar/CalendarView.vue
  src/views/calendar/component/CalendarViewModal.vue
  vite.config.js
Labels: feat✨, FrontEnd🖌️

#29 프론트 비율 수정 및 토큰에서 정보추출
  .gitignore
  package-lock.json
  package.json
  src/plugins/axios.js
  src/router/index.js
  src/stores/auth.js
  src/views/user/Mypage.vue
  src/views/user/PassWordChange.vue
Labels: fix🛠️, FrontEnd🖌️

#32 회의실 구현
  package-lock.json
  package.json
  src/router/index.js
  src/router/meetingroom.js
  src/views/Meetingroom/Meetingroom.vue
  src/views/Meetingroom/MeetingroomReservation.vue
Labels: feat✨, FrontEnd🖌️

#30 [채팅] 채팅 목록 기본 설계
  package-lock.json
  package.json
  src/components/layout/Navigation.vue
  src/views/chat/ChatRoom.vue
  src/views/chat/ChatRoomList.vue
  src/views/chat/chat_components/NewChatRoom.vue
  vite.config.js
Labels: feat✨, FrontEnd🖌️

#38 메인페이지 틀과 비서 기능 추가
  package-lock.json
  package.json
  src/App.vue
  src/assets/images/assistant.png
  src/components/Assistant.vue
  src/main.js
  src/router/index.js
  src/stores/assistant.js
  src/views/user/Main.vue
Labels: feat✨, FrontEnd🖌️

#42 feat: Kanban board
  src/views/workspace/WorkspaceView.vue
  src/views/workspace/views/CalendarView.vue
  src/views/workspace/views/KanbanBoardView.vue
Labels: feat✨, FrontEnd🖌️

#43 검색 시 나온 결과를 누르면 라우터를 통해 이동
  package-lock.json
  src/components/Assistant.vue
  src/main.js
  src/views/search/SearchResult.vue
  src/views/search/components/ProjectSearch.vue
  src/views/search/components/WorkspaceSearch.vue
Labels: feat✨, fix🛠️, FrontEnd🖌️

#44 [메인페이지] 메인페이지 달력 기능 추가
  src/views/user/Main.vue
  src/views/user/components/MainCalendar.vue
  src/views/user/components/ScheduleInvitaion.vue
Labels: feat✨, FrontEnd🖌️
